#!/usr/bin/eve python
# Author ID: jkbrar14

def write_name():
	name = input("Enter your name: ")
	filename = "my_name.txt"
	f = open(filename, "w")
	write_data = f.write(name)
	print(f"{filename} has been created)
write_name()

def helloWorld():
	print(‘Hello World’)


helloWorld()
